### ISSUE TITLE
Packges installed by brew and packages.yaml : do we need full path?

### ISSUE THREAD

**Issue by pramodskumbhar** [pramodskumbhar/spack-configs#8]
When install package with brew, we get:

```
For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig
```

Currently our `packages.yaml` has:

```
    openssl:
        paths:
            openssl@system: /usr/local
        buildable: False
        version: [system]
```

Do we need to put proper path i.e. ` /usr/local/opt/openssl` ? Currently this is not required but story on linux is different due to multi-arch.

**Comment by pramodskumbhar** [comment]
yes...most likely because of some tcl module limitations!

If we have specification like  : 

```
     mpich:
         paths:
             mpich@3.0.4: /usr
         version: [3.0.4]
         buildable: False
```

When we will do `module load` then `/usr/bin` is not added to `$PATH` because it already exist. But if we do `module purge` then it will be removed! And this will be annoying!

For `brew` it's fine because packages have `real` prefix under `/usr/local/opt/openmpi/` etc. and hence not a big issue. For linux where stuff goes into `/usr/` we have to make sure to either adjust paths or re-do PATH like : 

```
 module purge

# temporary workaround for module limitation
export PATH=/usr/bin:/usr/local/bin:$PATH
PATH=$(echo "$PATH" | awk -v RS=':' -v ORS=":" '!a[$1]++')
```
